doc_comment_code_block_width = 80
format_code_in_doc_comments = true
format_strings = true
group_imports = "One"
hard_tabs = false
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 80
merge_derives = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 0
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
