[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
buildstructor = { version = "0.6.0", default-features = false }
diesel.workspace = true
diesel-async = { version = "0.7.4", features = [
  "deadpool",
  "pool",
  "postgres",
  "tokio",
], default-features = false }
